# Generated by Django 4.2.5 on 2023-09-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
