# Generated by Django 4.2.5 on 2023-09-23 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlisting_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='liked',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='user_favoured', to=settings.AUTH_USER_MODEL),
        ),
    ]
