# Generated by Django 4.2.5 on 2023-09-24 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionlisting_liked_auctionlisting_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
