# Generated by Django 4.2.5 on 2023-10-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_like_user_followers_user_following_post_like_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
